### PR TITLE
Maven

### PR DESCRIPTION
**Pull request by ftomassetti**
Hi, in this patch I add a pom.xml and organize the code according to the Maven structure.
I correct a few things to make it compile. There are still a few compilation errors to solve but they are not so many.

### CODE REVIEW

**Comment by pcgomes** [comment]
Hi @ftomassetti , which is the OpenJDK version that you are compiling against? Because I am using the 1.7.0 (build 85), and the namespace changes that you have inserted are not allowing me to compile. The issue has been the dependency on "com.sun.tools.javac.code.TypeTag", which is not present in my version.

How do we fix this? Should we define a standard baseline for the OpenJDK version that we support?

**Comment by ftomassetti** [comment]
Hi @pcgomes sorry for causing this issue! Yes I was using the Sun JDK 1.8. The problem with these internal classes is that they are not compatible among versions. Maybe we can use reflection to see if a certain class is present (e.g., TypeTag) and depending on this class being present or not we can use different approaches. I think the changes between our two JDKs are not big (mainly this TypeTag thing) so we can isolate them somehow.

Or as an alternative we say we just support a specific version of the JDK (Sun/OpenJDK 1.7/1.8) but this would be more limited.

**Comment by pcgomes** [comment]
Hi @ftomassetti, I think the reflection approach to be too clumsy. I prefer to support some specific version. In this case, I'd suggest the latest (1.8), given its expected longer life-cycle (from now on). However, it would be nice if this is compatible with the next version of JavaParser.

Do you have some guess off which will be the supported version of the next major release of JavaParser?

**Comment by ftomassetti** [comment]
The current JavaParser version is 2.1 and it is able to parse Java 8. Next versions of JavaParser will be still compatible with Java 8 but anyway we can keep using the current version of JavaParser even if new comes out. The only issue is the JDK version because we have to ask the user to install it, while JavaParser and the other libraries are installed by Maven without any effort for the user.

Yes, the reflection could be a bit clumsy. Maybe we can start supporting one specific JDK version and than see in the future if we can find a way to easily supports other versions.

**Comment by pcgomes** [comment]
OK, so we agree to support one specific major OpenJDK version, which is OpenJDK 8.

I will download it now, and see what are the compilation errors that you have mentioned.

**Comment by pcgomes** [comment]
Done @ftomassetti.  It now compiles (at least for me) smoothly for OpenJDK8. Could you please check?

**Pull request merged**
